apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: infra-configs
  retryInterval: 8m 
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./monitoring/controllers/dev
  prune: true
