apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir
  namespace: storage
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  interval: 1h
  values:
    nfs:
      path: /export/nasdata
      server: 10.6.6.22
    storageClass:
      defaultClass: true

