apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      version: "1.18.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  interval: 1h
  values:
    additionalArguments:
    - --entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    deployment:
      enabled: true
      kind: Deployment
      replicas: 2
    k8sServiceHost: 10.6.6.247
    k8sServicePort: 6443
    kubeProxyReplacement: true
